### ISSUE TITLE
Subscriptions not working, if Sub.none is returned by the first call

### ISSUE THREAD

**Issue by jatinderjit** [elm/compiler#1762]
I tried to write a [clock application]( https://gist.github.com/jatinderjit/f225bdba21146bba09ad74387bf6863e).

If I return `Sub.none` in the first call to subscriptions, then the subsequent call to subscriptions does not do anything. But if I return a dummy subscription, then everything works fine.

In the mentioned gist, if I replace [`Time.every 1 NoOp`](https://gist.github.com/jatinderjit/f225bdba21146bba09ad74387bf6863e#file-clock-elm-L81) with [`Sub.none`](https://gist.github.com/jatinderjit/f225bdba21146bba09ad74387bf6863e#file-clock-elm-L80), the clock doesn't work.  The [`NoOp`](https://gist.github.com/jatinderjit/f225bdba21146bba09ad74387bf6863e#file-clock-elm-L44) message does nothing.

I tried to debug the JS, and `subscriptions` does return the *subscription object*, but `update` is not called after that.

**Comment by adeschamps** [comment]
Here's your example as an Ellie: https://ellie-app.com/38yPbFdvv6qa1

If you open the Elm debugger, then it begins to work.

**Comment by JaSpa** [comment]
As I encountered the problem myself, I took my browser's JS debugger and stepped through the generated code. I think the problem is that _older subscriptions can overwrite newer subscriptions._ This can happen if the command returned from the `init` function alters the model in such a way that the subscriptions change.

Ideally the execution flow would be

1. Call to `init` getting the first model
2. Setting subscriptions _based on the first model_
3. Executing the command returned from `init`
4. Call to `update` getting a new model
5. Setting subscriptions _based on the new model_
6. Executing the returned command
7. etc. …

But it can happen that it is instead

1. Call to `init` getting the first model
2. Executing the command returned from `init`
3. Call to `update` getting a new model
5. Setting subscriptions _based on the new model_
2. Setting subscriptions _based on the first model_ 

I don't know if I am correct but my guess would be that the problem is in [`_Platform_dispatchEffects`](https://github.com/elm/core/blob/de38986116bd93affc1c7a12e548d1f01be9a9f1/src/Elm/Kernel/Platform.js#L212). In the `for-in` loop is no ordering between ports and commands.

**Comment by avh4** [comment]
This (or a very similar) issue was reported against the elm-test cli with a write-up of a diagnosis that seems to match JaSpa's diagnosis here: https://github.com/rtfeldman/node-test-runner/issues/274#issue-354530241
