### ISSUE TITLE
Ctrl + L doesn't clear Elm REPL

### ISSUE THREAD

**Issue by MatheusRich** [elm/compiler#1768]
Typing `ctrl + l` doesn't clear the console.

Example: 
```elm
> 1 + 1
2 : number

-- Now type (CTRL/CMD) + L

-- Nothing happens
```
## Environment
**OS:** Ubuntu 16.04 LTS / Arch Linux
**Elm:** 0.19.0

**Comment by evancz** [comment]
Did it do this in 0.18? I have not heard of this functionality before.

**Comment by MatheusRich** [comment]
@evancz On Slack some people said it worked (on both 0.18 and 0.19).

**Comment by evancz** [comment]
I'm not sure I understand the issue. Can you investigate further, and when you can confirm it exists for other users, open a new issue explaining what you found. I have not used ctrl+l before, but I think I see what you want to do with that.

**Comment by rlefevre** [comment]
Usually pressing `CTRL-L` in a unix terminal clears it, like typing the `clear` command.
This does not work with the 0.19 Linux binary, however it works on other platforms (at least Mac OS X), it works with 0.18, and it also works when building the binary locally dynamically linked.

So this is most likely a side effect of the way the Linux x64 is built (using the Alpine Linux environment).
I also noticed that `DEL` does not work either (`CTRL-D` and `BACKSPACE` do though). Other shortcuts seem to work (`CTRL-A`, `CTRL-D`, `CTRL-K`, `CTRL-E`).

Sorry for that, I should have caught it during my tests. This could be related to the terminfo database used on Alpine, I am investigating...

**Comment by hecrj** [comment]
@rlefevre I cannot reproduce the issues you are describing with the latest binary installed using `npm` on Arch Linux:

```$ lsb_release -a
LSB Version:    1.4
Distributor ID: Arch
Description:    Arch Linux
Release:        rolling
Codename:       n/a
$ md5sum elm
8f945459724b4e2b86e583ce787f4f57  elm
```

`Ctrl-L` clears the REPL as expected and `DEL` works for me too.

**Comment by MatheusRich** [comment]
By the way, I installed 0.19 via the release package [available on github](https://github.com/elm/compiler/releases/). 

I'm gonna download it via npm on a Linux Mint and see what happens.

**Comment by MatheusRich** [comment]
By the way, I installed 0.19 via the release package [available on github](https://github.com/elm/compiler/releases/). 

I'm gonna download it via npm on a Linux Mint and see what happens.

**Comment by rlefevre** [comment]
Ok, it seems to happen when elm does not find the TERM terminfo definition in the database.
On Ubuntu 18.04, my terminal was using "xterm-256color" which does not exist in `ncurses-term`. 
The following fixes the issue:
```
$ sudo apt-get install ncurses
$ TERM=xterm-color elm repl
```
@MatheusRich , could you install `ncurses-term` and retry, and also tell us the output of `echo $TERM`.

Thank you

**Comment by rlefevre** [comment]
Ok, the problem seems to be that the Linux binary does not search for the terminfo database in `/lib/terminfo` where it is on Ubuntu. A workaround for now is to a symbolic link to it in the home directory:
```
ln -s /lib/terminfo ~/.terminfo
```
@MatheusRich , could you confirm that this works for you?

**Comment by rlefevre** [comment]
The root cause is that the `ncurses-static` package on Alpine Linux 3.7 [is built with](https://git.alpinelinux.org/cgit/aports/tree/main/ncurses/APKBUILD?h=3.7-stable):
```
--with-terminfo-dirs="/etc/terminfo:/usr/share/terminfo"
```
but some distributions (like Ubuntu 18.04 at least) have the terminfo database in `/lib/terminfo`.

A safer configuration would be:
```
--with-terminfo-dirs="/etc/terminfo:/lib/terminfo:/usr/share/terminfo:/usr/lib/terminfo"
```

I will contact the package maintainer to see if this can be improved, else we will have to build a docker image where this library is built with more `terminfo` directories.

**Comment by evancz** [comment]
@rlefevre, thank you so much for such a detailed investigation! ❤️

**Comment by rlefevre** [comment]
For the following reason:
1. Alpine Linux 3.7 seems to be in maintenance mode, and only security fixes will be accepted, so I don't think we will have a fix there that will help us.
2. Even with a fix in the Alpine package, the directories could be changed again later in the package (leading to a regression in elm), or we could need to add another one.

I think it is better to fix it in `elm` itsef. I made [this pull-request](https://github.com/elm/compiler/pull/1772) to offer some directions. Feel free to rewrite it as you wish.

**Comment by rlefevre** [comment]
Let me explain why in my opinion, I think this should be fixed in `elm` instead of asking users to configure it:

## 1 Additional configuration perception

On a distribution, packages using `readline` or `haskeline` (both use `terminfo`) are usually built on the same distribution, so the compiled-in directories to search for terminal description files are correct in linked `ncurses` library and the binaries find the terminal description without additional configuration. 

The `elm` Linux binary is actually correctly configured, but only for `Alpine Linux` on which it is built or distributions using the same directory to store `terminfo` files. 

Therefore asking users to do some additional configuration only for `elm` when all their other `readline/haskeline` applications work correctly may not be understood well, will be difficult to explain, and will degrade the first experience of users that are introduced to elm with its REPL (admittedly this is not atl all a critical issue either). It can be expected that some users would simply ignore the configuration instructions (if they find them).

At last, as `elm` is distributed as a single binary, it seems to me that it is its responsibility to work on most systems, not the one of the user, who is used to binaries built for its system by the packages maintainers.

## 2 Impacted Linux users proportion

As you can see in the following table, all Debian derivatives including Ubuntu ones since Debian 6 are impacted. Unfortunately, according to some [statistics](https://www.zdnet.com/article/whats-the-most-popular-linux-of-them-all/), this means that most Linux users would need some additional configuration to have the expected terminal behavior.

| Distribution | Terminal description found | Terminfo files directory|
|:-------------|:--------------------------:|:-----------------------:|
| Alpine 3.7 | :heavy_check_mark: | `/usr/share/terminfo` |
| Arch Linux | :heavy_check_mark: | `/usr/share/terminfo` |
| Centos 6.6 | :heavy_check_mark: | `/usr/share/terminfo` |
| Centos 7.5 | :heavy_check_mark: | `/usr/share/terminfo` |
| Debian 4 etch | :heavy_check_mark: | `/usr/share/terminfo` |
| Debian 5 lenny | :heavy_check_mark: | `/usr/share/terminfo` |
| Debian 6 squeeze | :x: | `/lib/terminfo` |
| Debian 7 wheezy | :x: | `/lib/terminfo` |
| Debian 9 stretch | :x: | `/lib/terminfo` |
| Fedora 26 | :heavy_check_mark: | `/usr/share/terminfo` |
| Fedora 28 | :heavy_check_mark: | `/usr/share/terminfo` |
| Gentoo | :heavy_check_mark: | `/usr/share/terminfo` |
| OpenSuse leap 15.0 | :heavy_check_mark: | `/usr/share/terminfo` |
| Slackware 14.2 | :heavy_check_mark: | `/usr/share/terminfo` |
| Ubuntu 14.04 |  :x: | `/lib/terminfo` |
| Ubuntu 16.04 |  :x: | `/lib/terminfo` |
| Ubuntu 18.04 |  :x: | `/lib/terminfo` |
| Ubuntu 18.10 (dev) |  :x: | `/lib/terminfo` |

## Additional notes
* the `TERMINFO_DIRS` environment variable used in the proposed patch is never set on systems as its purpose is to allow the users (not the system) to override the compiled-in directories searched for whatever reason. This is precisely what I propose to do inside the binary as the statically compiled-in set of directories is not large enough for all systems (and could change without prior warnings).

* As far as I can tell, I don't see a way to detect systems on which the binary compiled-in directories are not enough without some code more complex (and likely wrong) versus letting the `ncurses/terminfo` library do its job. So if we want to propose some additional configuration to the user, it should always be displayed by the binary or put on a website where it would be easy to miss.

* As I tried to explain, rebuilding the `ncurses` library with at least the additional Debian path is also a viable solution, but it seems to me that this is more burdensome for releases and the risk of later regression is more important. I can provide some directions though if this is wanted.

* At last, the directories set in the proposed patch is the largest one I found on the net. If you feel this is not necessary, we could at least merge the Alpine and Debian ones as it should cover most cases: ie `/etc/terminfo:/lib/terminfo:/usr/share/terminfo`.

**Comment by rlefevre** [comment]
This issue has been summarized in this new one:

https://github.com/elm/compiler/issues/1774

**Comment by BKSpurgeon** [comment]
@rlefevre Remi thank you for your excellent work.
