### ISSUE TITLE
Regression in 0.19: Using wildcard in elm make seems to result in compiler crash

### ISSUE THREAD

**Issue by alex-tan** [elm/compiler#1769]
In 0.18 the following would work with multiple root files in the elm directory:

`elm-make app/javascript/elm/*.elm --debug --output public/assets/javascripts/elm.js`

Now, in 0.19:

`elm make app/javascript/elm/*.elm --debug --output public/assets/javascripts/elm.js`

results in

```
elm make app/javascript/elm/*.elm --debug --output public/assets/javascripts/elm.js
Success! Compiled 2 modules.
elm: Map.!: given key is not an element in the map
CallStack (from HasCallStack):
  error, called at ./Data/Map/Internal.hs:610:17 in containers-0.5.11.0-K2TDqgYtGUcKxAY1UqVZ3R:Data.Map.Internal
```

even though compiling each elm file separately with `elm make` and running `elm make fileA fileB etc...` works in 0.19.

__Update:__ Only happens when --debug is passed in.

**Comment by alex-tan** [comment]
Nevermind, think this is a duplicate of #1753. Closing

**Comment by evancz** [comment]
In projects I manage, "duplicates" are considered "more data" and they lead to more perspectives and better understanding. I think it is best if folks just mention what they see, rather than spending time trying to make all the connections. That ends up making it harder for everyone!

So if you can create an http://sscce.org/ that triggers this error, please share it in a new issue.
