### ISSUE TITLE
Tail-calls in recursive functions are not optimized if used with pipeline operators

### ISSUE THREAD

**Issue by ymtszw** [elm/compiler#1770]
From slack discussion: https://elmlang.slack.com/archives/C13L7S5GR/p1535488054000100

In Elm 0.19. Reproducible in Ellie.

SSCCE:

```elm
module Main exposing (main)

import Browser
import Html

main : Program () () ()
main =
    Browser.sandbox
        { init = ()
        , update = \_ m -> m
        , view = \_ -> Html.text (tailCallWithPipeline 12345 "something")
        }

-- TCO Bug SSCCE

tailCallWithPipeline : Int -> String -> String
tailCallWithPipeline count acc =
    if count <= 0 then
        acc

    else
        acc
            |> tailCallWithPipeline (count - 1)


tailCallWithoutPipeline : Int -> String -> String
tailCallWithoutPipeline count acc =
    if count <= 0 then
        acc

    else
        tailCallWithoutPipeline (count - 1) acc
```

```html
<html>
<head></head>
<body>
  <main></main>
  <script>
    var app = Elm.Main.init({ node: document.querySelector('main') })
  </script>
</body>
</html>
```

Here, `tailCallWithPipeline` and `tailCallWithoutPipeline` are semantically identical recursive functions, the only difference is a use of pipeline operator `|>`.
However, executing `tailCallWithPipeline` ends up in runtime error: `RangeError: Maximum call stack size exceeded`, whereas `tailCallWithoutPipeline` does not (correctly optimized and run fine).

Both worked fine in 0.18.

**Comment by atdixon** [comment]
Here is another (smaller/repl-based) example:

```
> sum_ n i = if n == 0 then i else sum_ (n - 1) (n + i)
> sum_ 1000000 0
500000500000 : Int
```

HOWEVER, not if slightly modified using pipe operator:

```
> sum_ n i = if n == 0 then i else sum_ (n - 1) <| n + i
> sum_ 1000000 0
RangeError: Maximum call stack size exceeded
```

**Comment by evancz** [comment]
I am hesitant to call this a bug. In changing how code was generated in 0.19.0 to make sure the generated assets were really small, we moved some AST shuffling later into the optimization process. The old version tried to flatten out `<|` and `|>` uses earlier in the pipeline.

The resulting behavior is that tail-call elimination is only performed when the recursive call is in "tail call position" (i.e. called directly at the conclusion of some some branch of logic)

This particular optimization enters into the realm of feature because it can change program behavior, so it's definitely important to keep this stable. It looks like this behavior is going to remain the same from 0.19.0 to 0.19.1, and I think the best path is to just require the "tail call position" without any special exceptions for now.

**Comment by atdixon** [comment]
Is the change in behavior anything other than a "RangeError: Maximum call stack size exceeded"? I think it would be safe to say no client would be relying on this behavior and furthermore the behavior is likely widely variant across systems.

From the operator documentation, we have

> -- (arg |> func) is the same as (func arg)

But what seems to be suggested in your note is that this is not an equivalency. I may be missing something, but this is rather surprising behavior. A common refactoring relies on the expectation of this equivalency; that `(arg |> func)` and `(func arg)` are referentially transparent. But perform such refactoring in tail position and you're in for trouble?
