### ISSUE TITLE
Runtime exception in elm.js elm$time$Time$posixToMillis

### ISSUE THREAD

**Issue by z5h** [elm/compiler#1879]
I get a runtime exception in my compiled elm.js file at
```
var elm$time$Time$posixToMillis = function (_n0) {
	var millis = _n0.a;
	return millis;
};
```

This has happened a few times, but I'm not clear on the source of the problem to create an SSCCE. 

It happens when 
`Time.now |> Task.perform (\time -> AddAnimation { item = item, start = time })`
sets a time, and later this time is passed to `posixToMillis`.

Below is a stacktrace. I've preserved the elm.js should it be required for debugging.

The issue has happened most recently in Safari 12.0.2 (14606.3.4), elm 0.19.

<pre>
[Error] TypeError: undefined is not an object (evaluating '_n0.a')
	elm$time$Time$posixToMillis (elm.js:6426)
	(anonymous function) (elm.js:8455)
	(anonymous function) (elm.js:8317)
	(anonymous function) (elm.js:8326)
	(anonymous function) (elm.js:8468)
	(anonymous function) (elm.js:12757)
	(anonymous function) (elm.js:13470)
	sendToApp (elm.js:1868)
	(anonymous function) (elm.js:1978)
	_Scheduler_step (elm.js:1794)
	_Scheduler_enqueue (elm.js:1768)
	(anonymous function) (elm.js:1796)
	(anonymous function) (elm.js:4164)
</pre>

Notes:
- Only repeatable in Safari.
- Has not occurred with `--optimize` flag.

**Comment by evancz** [comment]
I do not know how to resolve this without an http://sscce.org/ so I am going to close. This is a pretty weird case, but that means having an SSCCE is even more important. Please open a new issue with an SSCCE if you can figure it out. Otherwise, it is really hard to rule out that it may be something about your OS or browser or plugins rather than something in Elm, and therefore unclear how much time to allocate to figuring it out from scratch.
