### ISSUE TITLE
event-stream: 404 Not Found

### ISSUE THREAD

**Issue by jwinnie** [elm/compiler#1907]
When attempting to install elm from yarn, I get this error:
```
error An unexpected error occurred: "https://registry.yarnpkg.com/event-stream/-/event-stream-3.3.6.tgz: Request failed \"404 Not Found\"".
```
Apparently, `event-stream` was a malware package: https://stackoverflow.com/questions/53578201/npm-err-404-not-found-event-stream3-3-6

## SSCCE
```
$ yarn global add elm
$ npm install -g elm
```

- **Elm:** latest
- **Operating System:** Ubuntu GNU/Linux 18.04

**Comment by evancz** [comment]
I asked the folks who were involved in making the `npm` installer, and this should not be a dependency of the Elm installer. We also could not duplicate it. I am going to close under the theory that this was a transient issue when folks found out that something went wrong with `event-stream`, but I don't know a lot about it. Please ask around in Elm Slack if you are seeing stuff. They may be able to help, and possible refine it into a new issue if the root cause is here.
