### ISSUE TITLE
Compiler crash when compiling with --debug

### ISSUE THREAD

**Issue by ananthb** [elm/compiler#1912]
**Quick Summary:**
The elm compiler crashes when I compile with --debug enabled, a program which has an Array in its Msg type.

## SSCCE

```elm
module Main exposing (Msg(..), main, update, view)

import Array
import Browser
import Html exposing (Html, div, text)


main =
    Browser.sandbox { init = Array.empty, update = update, view = Debug.todo "" }


type Msg
    = Update (Array.Array Int)


update msg model =
    case msg of
        Update arr ->
            arr
```

- **Elm:** 0.19
- **Browser:** Firefox
- **Operating System:** Windows 10

## Additional Details

Replacing the Array with a List in the Msg type fixes the crash.

*This does not crash when compiled with --debug*
```elm
module Main exposing (Msg(..), main, update, view)

import Browser
import Html exposing (Html, div, text)


main =
    Browser.sandbox { init = [], update = update, view = Debug.todo "" }


type Msg
    = Update (List Int)


update msg model =
    case msg of
        Update list ->
            list

```

**Comment by evancz** [comment]
Just tried this with my development build, and it works like normal now. This is because of changes from https://github.com/elm/compiler/commit/af2ea2b5baf6e47dcccca4385f6a773a981c6df2 which are described in a bit of additional detail [here](https://github.com/elm/compiler/pull/1850#issuecomment-509327575).

The fix should come out with 0.19.1, but there is still work left before everything else is ready.
