### ISSUE TITLE
documentation on tuple-overuse gives wrong link

### ISSUE THREAD

**Issue by silky** [elm/compiler#1938]
**Quick Summary:** broken link

### SSCE

in elm 0.19.0, consider the code:

```
tooBigToTuple = (1, 2, 3, 4, 5)
```

it fails with this message:

```
-- BAD TUPLE ------------------------------------------------------ src/Main.elm

I only accept tuples with two or three items. This has too many:

192| tooBigToTuple = (1, 2, 3, 4, 5)
                     ^^^^^^^^^^^^^^^
I recommend switching to records. Each item will be named, and you can use the
`point.x` syntax to access them.

Note: Read <https://elm-lang.org/0.19.0/tuples> for more comprehensive advice on
working with large chunks of data in Elm.
```

but the url it links me to looks like this:

![image](https://user-images.githubusercontent.com/129525/59086537-5f87e100-8945-11e9-8267-8ef382d24c18.png)

clearly broken. probably the wrong link?

**Comment by JDemler** [comment]
There is already a [PR](https://github.com/elm/elm-lang.org/pull/805) in `elm/elm-lang.org` fixing this.

**Comment by silky** [comment]
great

**Comment by evancz** [comment]
No problem to have multiple reports. Hearing about things from different perspectives is helpful.

**Comment by evancz** [comment]
I recently changed how these hint links worked. Instead of going direct to a page, there are redirects set up for each one. That way they can be updated more easily after a release and maintained as the hints changed over time.

So the link in question https://elm-lang.org/0.19.0/tuples should work now!

Thanks for the report!
