### ISSUE TITLE
Improve error message for elm install with a bad package name

### ISSUE THREAD

**Issue by ondrejsevcik** [elm/compiler#1941]
I made a typo in a package name when I tried to install it and it just showed me a stack trace. It took me a while to find that the issue is not my internet nor elm installation but a typo in a package name. 

```
❯ elm install NoRedInk/elm-json/decode-pipeline
elm: TODO show possible arg configurations
CallStack (from HasCallStack):
  error, called at ui/terminal/src/Terminal/Args/Error.hs:281:13 in main:Terminal.Args.Error
```

**Comment by evancz** [comment]
Based on the changes in https://github.com/elm/compiler/commit/a1c3e30f6157b08c8d18eb51c51e54f91cb47e83 I am now getting the following error locally:

```
> elm install NoRedInk/elm-json/decode-pipeline
I am having trouble with this argument:

    NoRedInk/elm-json/decode-pipeline

It is supposed to be a <package> value, like one of these:

    NoRedInk/elm-json-decode-pipeline
    NoRedInk/elm-decode-pipeline
    NoRedInk/elm-sortable-table
    allenap/elm-json-decode-broken

```

It's not perfect (since it does not filter the examples by compatibility with the `elm` version you are using at the moment) but it's definitely better!

Thanks for the report and nice SSCCE!
