### ISSUE TITLE
Map.! with kernel modules

### ISSUE THREAD

**Issue by Janiczek** [elm/compiler#1954]
**Quick Summary:** `Map.!` error when compiling a test `Main` file in a package with kernel modules

## SSCCE

https://github.com/Janiczek/elm-sscce-kernel-json/commits/master

- **Elm:** 0.19.1-alpha-3
- **Browser:** doesn't apply
- **Operating System:** Linux

## Additional Details

Our thread from #core-coordination - [link](https://elmlang.slack.com/archives/C13L7S5GR/p1563569800375000)

This is related to `elm/json` missing from deps causing problems, but with the twist that if you use kernel modules, even having `elm/json` doesn't help.
As said in the thread, this is the behaviour:

| elm/json | kernel module | crashes |
| --- | --- | --- |
| :x: | :x: | yes |
| :x: | :heavy_check_mark: | yes |
| :heavy_check_mark: | :x: | **NO** |
| :heavy_check_mark: | :heavy_check_mark: | yes |

**Comment by evancz** [comment]
I do not really understand the problem.

Does this manifests when someone installs a specific **published** `elm/*` project? If so, that is a bug in code generation. If not, the error messages for this kind of code are not very good because it's only used by `elm/*` packages. I don't think it makes sense to spend a bunch of time on error messages that will never trigger as a _user_ of the language.

Perhaps it makes sense to chat on Slack so I can get a clearer idea of what is going on here.

**Comment by Janiczek** [comment]
It is only triggered when **working on** `elm/*` or `elm-explorations/*` packages and trying stuff out with `main`-containing module, but those are still users of the language, even if not the ordinary ones. Eg. I imagine it would complicate stuff for Andrey and the WebGL repo.

It's a low-priority bug because of who is affected by it (ie. **not** ordinary users or package authors), but to me it still felt worth reporting.
