### ISSUE TITLE
Reconsider string interpolation (#905)

### ISSUE THREAD

**Issue by fifn2** [elm/compiler#1999]
**Quick Summary:** 
Consider revisiting the string interpolation syntax (#905).

## SSCCE
In react and other UI libraries, there's some kind of string interpolation.
```jsx
function Interpolate ({ val}) {
  return <div>Interpolation of {val}</div>
}
```
Why not elm?
```elm
import Html exposing (div)
view model = div [] [text "Hello {{ model.name }}. Nice to meet you!"]
```

Of course, I'm new to elm so I don't really know much, but the way I see it, es6 JavaScript kind of has the upper hand when it comes to string interpolation.

**Comment by evancz** [comment]
We try to use issues mostly for bugs and errors rather than for feature suggestions. It is often hard to reach a conclusion with feature suggestions, so they end up piling up over time.

We used to have a `toString : a -> String` function, but we found it led to problems in a decent number of cases. If you want to show a `Float` how many decimal places? If you want to show an `Int` should it be a compiler error if you are giving a `{ age : Int }` by accident? (IMO yes!)

We moved away from that design to having `Debug.toString` which cannot be used with `--optimized` code. The benefit of this is that we can have a faster and more compact runtime representation of Elm data. This led folks to use special purpose functions like `toEuros` in their code.

In the end, that means the ideal design would be one that does not do any implicit conversion at all, so the content of the interpolation would need to be a `String` type. At that point, the difference would be:

```elm
"It cost {{ toEuros money }} when on sale."
"It cost " ++ toEuros money ++ " when on sale."
```

Which isn't really such a great benefit for the cost of having `{{` be special characters.

Anyway, if you want to get more people's opinions, please ask about it on the slack or discourse! https://elm-lang.org/community
