### ISSUE TITLE
elm init is returning a 502 Bad Gateway error

### ISSUE THREAD

**Issue by CROC0** [elm/compiler#2051]
**Quick Summary:** ???
This is my first time using Elm so I installed the windows compiler. In VS Code I am running an elm init command and it is returning the following error message:

-- PROBLEM LOADING PACKAGE LIST ------------------------------------------------

I need the list of published packages before I can start initializing projects,
so I tried to fetch:

    https://package.elm-lang.org/all-packages

But it came back as 502 Bad Gateway

This may mean some online endpoint changed in an unexpected way, so if does not
seem like something on your side is causing this (e.g. firewall) please report
this to https://github.com/elm/compiler/issues with your operating system, Elm
version, the command you ran, the terminal output, and any additional
information that can help others reproduce the error!

When i enter the https://package.elm-lang.org/all-packages into my browser it also returns the same 502 Bad Gateway response.

I tried turning my firewall off and running the command although received the same error message

**Comment by Pdrevland** [comment]
Experience exactly same problem.

**Comment by roberth** [comment]
This is making Elm completely unusable in parceljs right now.

**Comment by mtonnberg** [comment]
Same here, we get the same error. Anyone know of a workaround or an ETA of a fix?

**Comment by dhbradshaw** [comment]
Visiting https://package.elm-lang.org/all-packages manually gives the same error.  ubuntu 502 bad gateway.

**Comment by joekinley** [comment]
Completely unusable right now. Development is at a complete halt, and if (god forbid) kubernetes decides to kill the pod, our platform will be unusable :(

**Comment by roberth** [comment]
I was able to finish up some work because [elm2nix](https://github.com/hercules-ci/elm2nix) caches the build inputs but it was annoying without hot module reloading. I was lucky that I didn't have to add a dependency because I don't think that works right now.

**Comment by groteck** [comment]
Same here, our deployment pipeline is also halt.

**Comment by evancz** [comment]
This has happened once before, but at a better time of day. That time, I spent the next few days setting up `monit` so that the server could restart itself.

In this case, it looks like the server went down at the worst possible time for US-based admin. We had `monit` set up to restart the server if this ever happened, but it ran into trouble. It seems that restarting needed the `HOME` environment variable to be defined, but it was not defined in whatever context `monit` was trying to run the restart script.

Anyway, once US work hours started again, we got the server back up. Then figured out what the problem was that prevented `monit` from working. So the issue reported here should be resolved as of a couple hours ago.

Additionally, I have added a new admin for the site who lives in Europe. Between these two things, I think the window of possible downtime should be a lot smaller. There will be an Elm event in Japan relatively soon, so perhaps we will be able to find someone there to add, further limiting the amount of time that are not covered by people at work.

**Comment by evancz** [comment]
For folks who had trouble with CI, it is possible with most systems to cache the `~/.elm` directory such that you do not need to talk to package.elm-lang.org or to github.com on the vast majority of builds.

People who had this configured did not experience any downtime on CI. I have asked community members to blog about this and make sure any default configurations out there are doing this.

We are hopeful the `monit` fix and the European admin will help with downtime, but configuring CI to save `~/.elm/` is a great way to be resilient to downtime elsewhere and to reduce build times in general.
