### ISSUE TITLE
Remove type alias keyword

### ISSUE THREAD

**Issue by pravdomil** [elm/compiler#2101]
The number one question on elm faq is:  
[What is the difference between type and type alias?](http://faq.elm-community.org/#what-is-the-difference-between-type-and-type-alias)

So what about having no type alias at all and replace this:
```elm
type alias MaybeList a = Maybe (List a)
```
with this:
```elm
MaybeList a = Maybe (List a)
```

Since variables and types are distinguish by first upper/lower case, we know if that is function or type alias.

This way elm will become even more compact.

**Comment by evancz** [comment]
There are no plans to change the syntax for `type` and `type alias` at this time.

I believe the kind of syntax you are suggesting exists in Agda or Idris, where the whole idea is that types work more like values. I agree that this is cool and more compact, but I think it is worth learning the distinction between a `type` and a `type alias` and clearly marking it. Especially because it has implications for whether recursion is allowed in such a declaration.
