### ISSUE TITLE
Support for aarch64/ARMv8/ARM64 architecture

### ISSUE THREAD

**Issue by mirobertod** [elm/compiler#2117]
Hello,
according to this issue #2007 I'd like to add one more use case for aarch64/ARMv8/ARM64 architecture.

I think ARM architecture will be more implemented in the next future, both in consumer and business environment.
Nowadays, we can see most of the open-source softwares have ARM binaries and cloud computing companies like AWS [are investing in this architecture](https://aws.amazon.com/blogs/aws/new-m6g-ec2-instances-powered-by-arm-based-aws-graviton2/). Currently we are not able to migrate our infrastructure on ARM because few our dependencies don't support it. (or there are not pre-compiled binaries)

I'll be glad if in the future there will be available an ARM binary for _elm_.
Thank you.

**Comment by rlefevre** [comment]
@mirobertod When you say "we are not able to migrate our infrastructure on ARM", you mean CI infrastructure right? Because once compiled to JavaScript, elm apps can of course be hosted on any architecture.

Note that for now you can find unofficial 32bit ARM binaries for elm here:
https://github.com/dmy/elm-raspberry-pi
They might work on aarch64 on a multi-arch OS with the appropriate 32bit libraries.

**Comment by mirobertod** [comment]
@rlefevre Yes, I mean in CI. We would like to have the same architecture in CI and the other environments. If we plan to migrate to ARM, we should build our binaries on ARM.

As you suggested, we could build in x64 and then move the compiled files. It would be nice to be able to do that on the same architecture.

Thanks

**Comment by whatevergeek** [comment]
glad to see an initiative on this!

**Comment by whatevergeek** [comment]
> glad to see an initiative on this!
> 
> i'm running ghc 8.4.4 on my arm64 android phone...
> i've got high hopes for this :-)



> glad to see an initiative on this!
> 
> i'm running ghc 8.4.4 on my arm64 android phone...
> i've got high hopes for this :-)

i was about to attempt and build elm on my arm64 phone... but saw this: https://github.com/elm/compiler/issues/1949

hope there's a way to run on arm64 soon...

**Comment by asonix** [comment]
FWIW I just set up an ubuntu 20.04 aarch64 container to use elm on my pinebook pro, and posted about it here: https://github.com/elm/compiler/issues/2141#issuecomment-751427003

I'm disappointed there hasn't been any movement on publishing "build from source" instructions, because one of the cited reasons was "the haskell compiler is always releasing new versions" but the steps of
```
$ rm worker/elm.cabal
$ cabal new-update
$ cabal new-configure --ghc-option=split-sections
$ cabal new-build
```
that I pulled from the elm raspberry pi repo for raspbian worked fine for me on ubuntu 20.04 as well for producing an Elm 19.1 binary.

Further, there's reasoning that "install methods are changing" which I assume is referring to appimage/snap/flatpak/apt/dnf/pacman/etc for linux package management, and to that I say:

Packaging Elm for X distro is not the job of the Elm project. People who are interested will package and distribute it. It does not stop the Elm project from making a binary download available, and it does not stop the Elm project from only documenting the binary download as the blessed install method. I would prefer Elm be packaged by the distro I use so I can manage it via my distro's package manager than to download a binary from a website, even if that's not a documented or official way to install Elm.

**Comment by LuisFX** [comment]
I work for in a small development team trying to make better use of mobile devices as experiment/hobby/light development (using userland under Dex or similar desktop mode). We get by coding F#, C# and JavaScript. We have been trying to compile for ARM64 to no avail, and I think after finding [#1949 ], we're going to take a small break from it 🤕 

Hopefully smarter people than us can make some progress.

**Comment by evancz** [comment]
This is a good scenario. I added it to #2007 and closing here. Thank you to @mirobertod for reporting this!

To the other commenters, I added a link to https://github.com/elm/compiler/blob/master/installers/linux/Dockerfile to #1949 for people who want to build from source. I think that's the closest thing to instructions that we'll be able to maintain, since it only aims to work in a very specific scenario. Perhaps that can help people figure out their specific scenario.
