### ISSUE TITLE
ARM64 Usecase - PinePhone/PineBook Pro

### ISSUE THREAD

**Issue by Razzeee** [elm/compiler#2141]
As https://github.com/elm/compiler/issues/2007 asks for more usecases, here's one that will probably become relevant for me in the future.

I bought a pine phone https://store.pine64.org/product/pinephone-community-edition-manjaro-with-convergence-package-limited-edition-linux-smartphone/ that you can not only use as a phone, but also as a desktop with a docking station.

There's also the pinebook pro, that is running an arm cpu https://store.pine64.org/product/14%e2%80%b3-pinebook-pro-linux-laptop-ansi-us-keyboard-estimated-dispatch-in-december-2019/

**Comment by MarkuBu** [comment]
I'm using an Odroid-N2 for a lot of my development. Would be nice to be able to compile Elm to this platform or download a precompiled ARM binary

**Comment by asonix** [comment]
FWIW I just spent a bit of time getting elm working on Manjaro on the Pinebook Pro. It involves using podman with rootless containers, but you can do it with docker too. The reason for this is I needed a haskell compiler and manjaro doesn't package one for arm but Ubuntu does.

Here's my dockerfile (I hope it's legible):
![image](https://user-images.githubusercontent.com/5304643/103164258-92672380-47ce-11eb-8cd4-3c70e72bca03.png)

Build it with this command:
`$ podman build -t elm-arm64 -f Dockerfile .`

And then I added an alias to my zshrc:
```zsh
alias elm="podman run --rm -it -w /elm -v ./:/elm -p 8000:8000 localhost/elm-arm64 /usr/bin/elm"
```

If you're using docker instead of podman, I believe you should add `-u $UID:$GID` to the `docker run` command, but I haven't tested that so if you end up doing this with docker instead of podman, please post about it.

After that, you can run `elm init`, `elm reactor`, etc and it should all Just Work :tm:

**Comment by evancz** [comment]
Added to https://github.com/elm/compiler/issues/2007. Thank you!
