### ISSUE TITLE
problem with Skinney/murmur3 

### ISSUE THREAD

**Issue by nathtale** [elm/compiler#2142]
-- PROBLEM DOWNLOADING PACKAGE -------------------------------------------------

I was trying to download the source code for Skinney/murmur3 2.0.8, so I tried
to fetch:

    https://github.com/Skinney/murmur3/zipball/2.0.8/

But it came back as 404 Not Found

This may mean some online endpoint changed in an unexpected way, so if does not
seem like something on your side is causing this (e.g. firewall) please report
this to https://github.com/elm/compiler/issues with your operating system, Elm
version, the command you ran, the terminal output, and any additional
information that can help others reproduce the error!

**Comment by lydell** [comment]
You can find more information here: https://discourse.elm-lang.org/t/skinney-murmur3-not-downloading/6285

**Comment by nathtale** [comment]
ok thanks

**Comment by nathtale** [comment]
The dependencies in your elm.json are not compatible.

Did you change them by hand? Try to change it back! It is much more reliable to
add dependencies with elm install or the dependency management tool in
elm reactor.

Please ask for help on the community forums if you try those paths and are still
having problems!

**Comment by Razzeee** [comment]
You can probably use https://github.com/zwilias/elm-json to make that change, that's at least what I've read.

**Comment by emarich** [comment]
> You can probably use https://github.com/zwilias/elm-json to make that change, that's at least what I've read.

I have same issue as nathtale, I tried it uninstall it with elm-json, but actually nothing happend and when I tried to manualluy delete it, I can't run code, because of error:  

>The dependencies in your elm.json are not compatible.
Did you change them by hand? Try to change it back! It is much more reliable to
add dependencies with elm install or the dependency management tool in
elm reactor.
Please ask for help on the community forums if you try those paths and are still
having problems!
