### ISSUE TITLE
foldl seems to be defined incorrectly

### ISSUE THREAD

**Issue by jcollard** [elm/compiler#346]
`foldl (/) 10 [2,4]` should produce 1.25 but produces 20

http://share-elm.com/sprout/5286e4e9e4b06194fd2d20bf

**Comment by MrRacoon** [comment]
@evancz I understand why changing the type signature made the function more accessible in a way. But I can't help but feel like the main point of `foldl` was lost because of this decision.

In haskell we learn the diff between fold(l/r) looks like this:
```
foldl :: (b -> a -> b) -> a -> [b] -> b
f(f(f(z, 1), 2), 3)

foldr :: (a -> b -> b) -> a -> [b] -> b
f(1, f(2, f(3, z)))
```

But with the decision of elm here, we get:

```
foldl :: (a -> b -> b) -> a -> [b] -> b
f(3, f(2, f(1, z)))

foldr :: (a -> b -> b) -> a -> [b] -> b
f(1, f(2, f(3, z)))
```

Does that not feel like elm tossed out a fundamental reduction pattern? Your foldl now is really just a foldr with a quick `reverse` before the application. when I explain this to others, i kinda feel like some of the beauty gets lost.

**Comment by jfmc** [comment]
Curiously many Prolog implementations use in foldl/N definitions the same argument order than in Elm, to favor the accumulator behavior. I wonder if there exists other languages doing it.

**Comment by OvermindDL1** [comment]
Both Elixir and Erlang use the `elementType -> accumulatorType -> accumulatorType` style like Elm as well, though they are based on the Prolog style too.
